[project]
name = "pyborg"
version = "2.1.0a2"
description = "Markov chain (chat) bot for a suite for modern services (discord, irc, twitter, mastodon, file, linein)"
license = "GPL-3.0-or-later"
readme = "pyborg/README.md"
authors = [{name = "J Laxson", email = "<jackjrabbit@gmail.com>"}]
dynamic = ["classifiers", "requires-python", "dependencies"]

[project.urls]
Repository = "https://github.com/jrabbit/pyborg-1up"
Documentation = "https://pyborg.readthedocs.io/en/latest/"

[tool.poetry]
include = ["example.*.toml"]
packages = [
    { include = "pyborg", from = "pyborg" },
    { include = "pyborg_entrypoint.py", from = "pyborg" },
]
classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Topic :: Communications :: Chat :: Internet Relay Chat",
    "Topic :: Games/Entertainment",
]
[poetry.scripts]
pyborg = 'pyborg_entrypoint:cli_base'

[tool.poetry.dependencies]
python = "^3.8"
toml = "^0.10.0"
arrow = "^1"
PyTumblr = "^0.1.0"
requests = "*"
bottle = "^0.12.17"
venusian = "^3"
click = "^8.0"
humanize = "^3.0"
praw = "^6.3"
"Mastodon.py" = "<1.5"
tweepy = "^3.7"
attrs = "^25"
statsd = "^3.3"
prompt_toolkit = "^3"
"discord.py" = "^2"
"aeidon" = {version= "^1.7.0", optional = true}
irc = "^19"
aiohttp = "*"
nltk = {version = "^3.4.5", optional = true}
tabulate = "^0.8.5"
filelock = "^3.0"
importlib_resources = {version = "*", python = "< 3.9"}
networkx = {version = "^2.4", optional = true}
matplotlib = {version = "^3.1.2", optional = true}
typing_extensions = "^4"
defusedxml = "^0.7.0"
systemd = {version = "^0.16.1", optional = true}
pysocks = "^1.7.1"
pydot = {version = "^1.4.1", optional = true}
pygraphviz = {version = "^1.7", optional = true}

[tool.poetry.group.nlp]
optional = true
[tool.poetry.group.nlp.dependencies]
nltk = "^3.4.5"
[tool.poetry.group.subtitles]
optional = true
[tool.poetry.group.subtitles.dependencies]
aeidon = "^1.7.0"
[tool.poetry.group.systemd]
optional = true
[tool.poetry.group.systemd.dependencies]
systemd = "^0.16.1"
[tool.poetry.group.graphing]
optional = true
[tool.poetry.group.graphing.dependencies]
matplotlib = "^3.1.2"
pydot = "^1.4.1"
pygraphviz =  "^1.7"
networkx = "^2.4"


[tool.poetry.group.dev.dependencies]
green = "*"
coverage = "*"
sphinx-click = "*"
sphinx-autobuild = "*"
mypy = "*"
flake8 = "^3.7"
invoke = "^2.2"
fabric2 = "^3"
asynctest = "^0.13.0"
ipython = "^8"
docutils = "*"
pylint = "^3"
bandit = "*"
sphinxcontrib_github_alt = "^1.2"
webtest = "*"
tox = "*"

[tool.poetry.group.dev.dependencies.black]
version = "*"
allow-prereleases = true

[tool.isort]
known_third_party = ["aeidon"]
line_length = 140

[tool.black]
line-length = 140

[tool.pyright]
ignore = ["*/misc/*", "**/test/*"]
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
